# Generated by Django 6.0.2 on 2026-02-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market_App', '0002_category_alter_product_options_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
